/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#00236f",
        "primary-container": "#1e3a8a",
        "on-primary": "#ffffff",
        "primary-fixed": "#dce1ff",
        "primary-fixed-dim": "#b6c4ff",
        "secondary": "#49607c",
        "secondary-container": "#c7dfff",
        "secondary-fixed": "#d1e4ff",
        "secondary-fixed-dim": "#b0c9e8",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#011d35",
        "on-secondary-fixed-variant": "#314863",
        "tertiary": "#00311f",
        "tertiary-container": "#004a31",
        "tertiary-fixed": "#6ffbbe",
        "tertiary-fixed-dim": "#4edea3",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#27c38a",
        "on-tertiary-fixed-variant": "#005236",
        "surface": "#f9f9ff",
        "surface-bright": "#f9f9ff",
        "surface-dim": "#cfdaf2",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f0f3ff",
        "surface-container": "#e7eeff",
        "surface-container-high": "#dee8ff",
        "surface-container-highest": "#d8e3fb",
        "surface-variant": "#d8e3fb",
        "background": "#f9f9ff",
        "on-background": "#111c2d",
        "on-surface": "#111c2d",
        "on-surface-variant": "#444651",
        "outline": "#757682",
        "outline-variant": "#c5c5d3",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "inverse-surface": "#263143",
        "inverse-on-surface": "#ecf1ff",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "gutter": "1.5rem",
        "margin": "2rem",
      },
    },
  },
  plugins: [],
};
